[package]
name = "marketplace"
edition = "2024.beta"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }
issuerregistry = { local = "../issuerregistry" }
rwaasset = { local = "../rwaasset" }
admin = { local = "../admin" }

[addresses]
marketplace = "0x5a103ccfaff901c4be1eaf6592f4c3e9e0e4fea33cdcb5cb7ec3fc205aa3ef79"
rwaasset = "0xd64e54e9e5368e88c46403815a13eb1eb3d6301c8438650767778ee1bc35b8e6"
issuerregistry = "0x76b6231c5563e29bac3e0db19be4f8f8f79106498588eeda40fde55581ee4aa2"
admin = "0xcbb42645cd33641692de2777084d81cb48f297781bb1fed43ef6e18c33a448de"

# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
